# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'untitled.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QToolBar, QWidget)
import icons_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1050, 582)
        MainWindow.setStyleSheet(u"/* Barra de ferramentas */\n"
"QToolBar {\n"
"    background-color: #ffffff; /* Cinza claro */\n"
"}\n"
"\n"
"/* Barra de menu */\n"
"QMenuBar {\n"
"    background-color: #f0f0f0; /* Cinza claro */\n"
"}\n"
"\n"
"/* Restante do background */\n"
"QMainWindow {\n"
"    background-color: #ffffff; /* Branco */\n"
"}\n"
"")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/icons/607674.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew.setIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u":/icons/32743.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionOpen.setIcon(icon1)
        self.actionPDF = QAction(MainWindow)
        self.actionPDF.setObjectName(u"actionPDF")
        icon2 = QIcon()
        icon2.addFile(u":/icons/pdf.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPDF.setIcon(icon2)
        self.actionPNG = QAction(MainWindow)
        self.actionPNG.setObjectName(u"actionPNG")
        icon3 = QIcon()
        icon3.addFile(u":/icons/3342137.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPNG.setIcon(icon3)
        self.actionJPG = QAction(MainWindow)
        self.actionJPG.setObjectName(u"actionJPG")
        self.actionJPEG = QAction(MainWindow)
        self.actionJPEG.setObjectName(u"actionJPEG")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon4 = QIcon()
        icon4.addFile(u":/icons/1176943.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave.setIcon(icon4)
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        icon5 = QIcon()
        icon5.addFile(u":/icons/impressora.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrint.setIcon(icon5)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        icon6 = QIcon()
        icon6.addFile(u":/icons/del.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete.setIcon(icon6)
        self.actionShow_side_bar = QAction(MainWindow)
        self.actionShow_side_bar.setObjectName(u"actionShow_side_bar")
        self.actionShow_Toolbar = QAction(MainWindow)
        self.actionShow_Toolbar.setObjectName(u"actionShow_Toolbar")
        self.actionPresentation_Mode = QAction(MainWindow)
        self.actionPresentation_Mode.setObjectName(u"actionPresentation_Mode")
        self.actionFullscreen = QAction(MainWindow)
        self.actionFullscreen.setObjectName(u"actionFullscreen")
        self.actionShow_Hide_Menubar = QAction(MainWindow)
        self.actionShow_Hide_Menubar.setObjectName(u"actionShow_Hide_Menubar")
        self.actionEnlarge = QAction(MainWindow)
        self.actionEnlarge.setObjectName(u"actionEnlarge")
        self.actionRudce = QAction(MainWindow)
        self.actionRudce.setObjectName(u"actionRudce")
        self.actionNormal_Size = QAction(MainWindow)
        self.actionNormal_Size.setObjectName(u"actionNormal_Size")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.actionCredits = QAction(MainWindow)
        self.actionCredits.setObjectName(u"actionCredits")
        self.actionNext_Page = QAction(MainWindow)
        self.actionNext_Page.setObjectName(u"actionNext_Page")
        icon7 = QIcon()
        icon7.addFile(u":/icons/109617.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNext_Page.setIcon(icon7)
        self.actionPrevious_Page = QAction(MainWindow)
        self.actionPrevious_Page.setObjectName(u"actionPrevious_Page")
        icon8 = QIcon()
        icon8.addFile(u":/icons/120826.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrevious_Page.setIcon(icon8)
        self.actionNew_Page = QAction(MainWindow)
        self.actionNew_Page.setObjectName(u"actionNew_Page")
        icon9 = QIcon()
        icon9.addFile(u":/icons/page.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew_Page.setIcon(icon9)
        self.actionDelete_Page = QAction(MainWindow)
        self.actionDelete_Page.setObjectName(u"actionDelete_Page")
        icon10 = QIcon()
        icon10.addFile(u":/icons/paged.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete_Page.setIcon(icon10)
        self.actionErase = QAction(MainWindow)
        self.actionErase.setObjectName(u"actionErase")
        icon11 = QIcon()
        icon11.addFile(u":/icons/5447777.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionErase.setIcon(icon11)
        self.actionText = QAction(MainWindow)
        self.actionText.setObjectName(u"actionText")
        icon12 = QIcon()
        icon12.addFile(u":/icons/99.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionText.setIcon(icon12)
        self.actionHighlighter = QAction(MainWindow)
        self.actionHighlighter.setObjectName(u"actionHighlighter")
        icon13 = QIcon()
        icon13.addFile(u"ICONES/80619.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHighlighter.setIcon(icon13)
        self.actionImage = QAction(MainWindow)
        self.actionImage.setObjectName(u"actionImage")
        icon14 = QIcon()
        icon14.addFile(u":/icons/image.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImage.setIcon(icon14)
        self.actionCircle = QAction(MainWindow)
        self.actionCircle.setObjectName(u"actionCircle")
        icon15 = QIcon()
        icon15.addFile(u":/icons/circle_geometry_container_icon_146007.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCircle.setIcon(icon15)
        self.actionsquare = QAction(MainWindow)
        self.actionsquare.setObjectName(u"actionsquare")
        icon16 = QIcon()
        icon16.addFile(u":/icons/2926335.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionsquare.setIcon(icon16)
        self.actionRectangle = QAction(MainWindow)
        self.actionRectangle.setObjectName(u"actionRectangle")
        self.actionTriangle = QAction(MainWindow)
        self.actionTriangle.setObjectName(u"actionTriangle")
        self.action_Ellipse = QAction(MainWindow)
        self.action_Ellipse.setObjectName(u"action_Ellipse")
        self.actionHighlighter_2 = QAction(MainWindow)
        self.actionHighlighter_2.setObjectName(u"actionHighlighter_2")
        icon17 = QIcon()
        icon17.addFile(u":/icons/80619.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionHighlighter_2.setIcon(icon17)
        self.actionEquilateral_Triangle = QAction(MainWindow)
        self.actionEquilateral_Triangle.setObjectName(u"actionEquilateral_Triangle")
        icon18 = QIcon()
        icon18.addFile(u":/icons/67351.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionEquilateral_Triangle.setIcon(icon18)
        self.actionRectangle_3 = QAction(MainWindow)
        self.actionRectangle_3.setObjectName(u"actionRectangle_3")
        self.action_Diamond = QAction(MainWindow)
        self.action_Diamond.setObjectName(u"action_Diamond")
        self.action_Trapeze = QAction(MainWindow)
        self.action_Trapeze.setObjectName(u"action_Trapeze")
        self.actionRight_Triangle = QAction(MainWindow)
        self.actionRight_Triangle.setObjectName(u"actionRight_Triangle")
        icon19 = QIcon()
        icon19.addFile(u":/icons/rT.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRight_Triangle.setIcon(icon19)
        self.action45 = QAction(MainWindow)
        self.action45.setObjectName(u"action45")
        self.action90 = QAction(MainWindow)
        self.action90.setObjectName(u"action90")
        self.action180 = QAction(MainWindow)
        self.action180.setObjectName(u"action180")
        self.action270 = QAction(MainWindow)
        self.action270.setObjectName(u"action270")
        self.action_Straight = QAction(MainWindow)
        self.action_Straight.setObjectName(u"action_Straight")
        icon20 = QIcon()
        icon20.addFile(u":/icons/line-png-16822.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.action_Straight.setIcon(icon20)
        self.actionCube = QAction(MainWindow)
        self.actionCube.setObjectName(u"actionCube")
        self.actionPiramid = QAction(MainWindow)
        self.actionPiramid.setObjectName(u"actionPiramid")
        self.actionBall = QAction(MainWindow)
        self.actionBall.setObjectName(u"actionBall")
        self.actionCone = QAction(MainWindow)
        self.actionCone.setObjectName(u"actionCone")
        self.action_Cylinder = QAction(MainWindow)
        self.action_Cylinder.setObjectName(u"action_Cylinder")
        self.actionBlue = QAction(MainWindow)
        self.actionBlue.setObjectName(u"actionBlue")
        self.actionBlack = QAction(MainWindow)
        self.actionBlack.setObjectName(u"actionBlack")
        self.actionRed = QAction(MainWindow)
        self.actionRed.setObjectName(u"actionRed")
        self.actionYellow = QAction(MainWindow)
        self.actionYellow.setObjectName(u"actionYellow")
        self.actionPurple = QAction(MainWindow)
        self.actionPurple.setObjectName(u"actionPurple")
        self.actionOrange = QAction(MainWindow)
        self.actionOrange.setObjectName(u"actionOrange")
        self.actionPink = QAction(MainWindow)
        self.actionPink.setObjectName(u"actionPink")
        self.actionCyan = QAction(MainWindow)
        self.actionCyan.setObjectName(u"actionCyan")
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        icon21 = QIcon()
        icon21.addFile(u":/icons/776203.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPen.setIcon(icon21)
        self.actionYellow_2 = QAction(MainWindow)
        self.actionYellow_2.setObjectName(u"actionYellow_2")
        self.actionPurple_2 = QAction(MainWindow)
        self.actionPurple_2.setObjectName(u"actionPurple_2")
        self.actionRed_2 = QAction(MainWindow)
        self.actionRed_2.setObjectName(u"actionRed_2")
        self.actionCian = QAction(MainWindow)
        self.actionCian.setObjectName(u"actionCian")
        self.actionCredits_2 = QAction(MainWindow)
        self.actionCredits_2.setObjectName(u"actionCredits_2")
        self.actionHelp_2 = QAction(MainWindow)
        self.actionHelp_2.setObjectName(u"actionHelp_2")
        self.actionHelp_3 = QAction(MainWindow)
        self.actionHelp_3.setObjectName(u"actionHelp_3")
        self.actionRectangle_2 = QAction(MainWindow)
        self.actionRectangle_2.setObjectName(u"actionRectangle_2")
        icon22 = QIcon()
        icon22.addFile(u"2926335.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRectangle_2.setIcon(icon22)
        self.actionstraight_line = QAction(MainWindow)
        self.actionstraight_line.setObjectName(u"actionstraight_line")
        self.actionstraight_line.setIcon(icon20)
        self.actionEllipse = QAction(MainWindow)
        self.actionEllipse.setObjectName(u"actionEllipse")
        self.actionEllipse.setIcon(icon15)
        self.actionLast_Page = QAction(MainWindow)
        self.actionLast_Page.setObjectName(u"actionLast_Page")
        icon23 = QIcon()
        icon23.addFile(u":/icons/setad.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionLast_Page.setIcon(icon23)
        self.actionFirst_Page = QAction(MainWindow)
        self.actionFirst_Page.setObjectName(u"actionFirst_Page")
        icon24 = QIcon()
        icon24.addFile(u":/icons/setade.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionFirst_Page.setIcon(icon24)
        self.actionDelete_Last_Page = QAction(MainWindow)
        self.actionDelete_Last_Page.setObjectName(u"actionDelete_Last_Page")
        icon25 = QIcon()
        icon25.addFile(u":/icons/lule.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete_Last_Page.setIcon(icon25)
        self.actionSave_as_PNG = QAction(MainWindow)
        self.actionSave_as_PNG.setObjectName(u"actionSave_as_PNG")
        icon26 = QIcon()
        icon26.addFile(u"3342137.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSave_as_PNG.setIcon(icon26)
        self.actionEnglish = QAction(MainWindow)
        self.actionEnglish.setObjectName(u"actionEnglish")
        self.actionPortugue_s = QAction(MainWindow)
        self.actionPortugue_s.setObjectName(u"actionPortugue_s")
        self.actionEspa_ol = QAction(MainWindow)
        self.actionEspa_ol.setObjectName(u"actionEspa_ol")
        self.actionSave_all_as_PNG = QAction(MainWindow)
        self.actionSave_all_as_PNG.setObjectName(u"actionSave_all_as_PNG")
        self.actionSave_as_PDF = QAction(MainWindow)
        self.actionSave_as_PDF.setObjectName(u"actionSave_as_PDF")
        self.actionHide_Cursor = QAction(MainWindow)
        self.actionHide_Cursor.setObjectName(u"actionHide_Cursor")
        self.actionSearch_Page = QAction(MainWindow)
        self.actionSearch_Page.setObjectName(u"actionSearch_Page")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setStyleSheet(u"")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1050, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuPage = QMenu(self.menubar)
        self.menuPage.setObjectName(u"menuPage")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuPen = QMenu(self.menuTools)
        self.menuPen.setObjectName(u"menuPen")
        self.menuHighlighter_Color = QMenu(self.menuTools)
        self.menuHighlighter_Color.setObjectName(u"menuHighlighter_Color")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuTranslation = QMenu(self.menuHelp)
        self.menuTranslation.setObjectName(u"menuTranslation")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPage.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as_PDF)
        self.menuFile.addAction(self.actionSave_as_PNG)
        self.menuFile.addAction(self.actionSave_all_as_PNG)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionPresentation_Mode)
        self.menuEdit.addAction(self.actionFullscreen)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionShow_Toolbar)
        self.menuEdit.addAction(self.actionShow_Hide_Menubar)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionDelete)
        self.menuPage.addAction(self.actionNew_Page)
        self.menuPage.addAction(self.actionDelete_Page)
        self.menuPage.addAction(self.actionDelete_Last_Page)
        self.menuPage.addSeparator()
        self.menuPage.addAction(self.actionNext_Page)
        self.menuPage.addAction(self.actionPrevious_Page)
        self.menuPage.addAction(self.actionLast_Page)
        self.menuPage.addAction(self.actionFirst_Page)
        self.menuPage.addSeparator()
        self.menuTools.addAction(self.actionPen)
        self.menuTools.addAction(self.menuPen.menuAction())
        self.menuTools.addAction(self.actionErase)
        self.menuTools.addAction(self.actionHighlighter_2)
        self.menuTools.addAction(self.menuHighlighter_Color.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionEllipse)
        self.menuTools.addAction(self.actionRectangle_2)
        self.menuTools.addAction(self.actionstraight_line)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionHide_Cursor)
        self.menuPen.addAction(self.actionBlue)
        self.menuPen.addAction(self.actionBlack)
        self.menuPen.addAction(self.actionRed)
        self.menuPen.addAction(self.actionYellow)
        self.menuPen.addAction(self.actionPurple)
        self.menuPen.addAction(self.actionOrange)
        self.menuPen.addAction(self.actionPink)
        self.menuPen.addAction(self.actionCyan)
        self.menuHighlighter_Color.addAction(self.actionYellow_2)
        self.menuHighlighter_Color.addAction(self.actionPurple_2)
        self.menuHighlighter_Color.addAction(self.actionRed_2)
        self.menuHighlighter_Color.addAction(self.actionCian)
        self.menuHelp.addAction(self.actionCredits_2)
        self.menuHelp.addAction(self.menuTranslation.menuAction())
        self.menuTranslation.addAction(self.actionEnglish)
        self.menuTranslation.addAction(self.actionPortugue_s)
        self.menuTranslation.addAction(self.actionEspa_ol)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_as_PDF)
        self.toolBar.addAction(self.actionSave_as_PNG)
        self.toolBar.addAction(self.actionSave_all_as_PNG)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLast_Page)
        self.toolBar.addAction(self.actionNext_Page)
        self.toolBar.addAction(self.actionPrevious_Page)
        self.toolBar.addAction(self.actionFirst_Page)
        self.toolBar.addAction(self.actionNew_Page)
        self.toolBar.addAction(self.actionDelete_Page)
        self.toolBar.addAction(self.actionDelete_Last_Page)
        self.toolBar.addAction(self.actionSearch_Page)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPen)
        self.toolBar.addAction(self.actionErase)
        self.toolBar.addAction(self.actionHighlighter_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionEllipse)
        self.toolBar.addAction(self.actionRectangle_2)
        self.toolBar.addAction(self.actionstraight_line)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHide_Cursor)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionPDF.setText(QCoreApplication.translate("MainWindow", u"PDF", None))
        self.actionPNG.setText(QCoreApplication.translate("MainWindow", u"PNG", None))
        self.actionJPG.setText(QCoreApplication.translate("MainWindow", u"JPG", None))
        self.actionJPEG.setText(QCoreApplication.translate("MainWindow", u"JPEG", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
#if QT_CONFIG(shortcut)
        self.actionPrint.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"F8", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"Clean Board", None))
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionShow_side_bar.setText(QCoreApplication.translate("MainWindow", u"Show/\n"
"Hide Sidebar", None))
        self.actionShow_Toolbar.setText(QCoreApplication.translate("MainWindow", u"Show/\n"
"Hide Toolbar", None))
#if QT_CONFIG(shortcut)
        self.actionShow_Toolbar.setShortcut(QCoreApplication.translate("MainWindow", u"F9", None))
#endif // QT_CONFIG(shortcut)
        self.actionPresentation_Mode.setText(QCoreApplication.translate("MainWindow", u"Presentation Mode", None))
#if QT_CONFIG(shortcut)
        self.actionPresentation_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"F10", None))
#endif // QT_CONFIG(shortcut)
        self.actionFullscreen.setText(QCoreApplication.translate("MainWindow", u"Fullscreen/Window Mode", None))
#if QT_CONFIG(shortcut)
        self.actionFullscreen.setShortcut(QCoreApplication.translate("MainWindow", u"F11", None))
#endif // QT_CONFIG(shortcut)
        self.actionShow_Hide_Menubar.setText(QCoreApplication.translate("MainWindow", u"Show/\n"
"Hide Menubar", None))
#if QT_CONFIG(shortcut)
        self.actionShow_Hide_Menubar.setShortcut(QCoreApplication.translate("MainWindow", u"F7", None))
#endif // QT_CONFIG(shortcut)
        self.actionEnlarge.setText(QCoreApplication.translate("MainWindow", u"Enlarge", None))
#if QT_CONFIG(shortcut)
        self.actionEnlarge.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionRudce.setText(QCoreApplication.translate("MainWindow", u"Ruduce", None))
#if QT_CONFIG(shortcut)
        self.actionRudce.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.actionNormal_Size.setText(QCoreApplication.translate("MainWindow", u"Normal Size", None))
#if QT_CONFIG(shortcut)
        self.actionNormal_Size.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
#if QT_CONFIG(shortcut)
        self.actionHelp.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionCredits.setText(QCoreApplication.translate("MainWindow", u"Credits", None))
#if QT_CONFIG(shortcut)
        self.actionCredits.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionNext_Page.setText(QCoreApplication.translate("MainWindow", u"Next Page", None))
#if QT_CONFIG(shortcut)
        self.actionNext_Page.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrevious_Page.setText(QCoreApplication.translate("MainWindow", u"Previous Page", None))
#if QT_CONFIG(shortcut)
        self.actionPrevious_Page.setShortcut(QCoreApplication.translate("MainWindow", u"F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_Page.setText(QCoreApplication.translate("MainWindow", u"New Page", None))
#if QT_CONFIG(shortcut)
        self.actionNew_Page.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Page.setText(QCoreApplication.translate("MainWindow", u"Delete Page", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Page.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.actionErase.setText(QCoreApplication.translate("MainWindow", u"Eraser", None))
#if QT_CONFIG(shortcut)
        self.actionErase.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionText.setText(QCoreApplication.translate("MainWindow", u"Text", None))
#if QT_CONFIG(shortcut)
        self.actionText.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.actionHighlighter.setText(QCoreApplication.translate("MainWindow", u"Highlighter", None))
        self.actionImage.setText(QCoreApplication.translate("MainWindow", u"Image", None))
        self.actionCircle.setText(QCoreApplication.translate("MainWindow", u"Circle", None))
        self.actionsquare.setText(QCoreApplication.translate("MainWindow", u"Square", None))
        self.actionRectangle.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
        self.actionTriangle.setText(QCoreApplication.translate("MainWindow", u"Triangle", None))
        self.action_Ellipse.setText(QCoreApplication.translate("MainWindow", u"\n"
"Ellipse", None))
        self.actionHighlighter_2.setText(QCoreApplication.translate("MainWindow", u"Highlighter", None))
#if QT_CONFIG(shortcut)
        self.actionHighlighter_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionEquilateral_Triangle.setText(QCoreApplication.translate("MainWindow", u"Equilateral Triangle", None))
        self.actionRectangle_3.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
        self.action_Diamond.setText(QCoreApplication.translate("MainWindow", u"\n"
"Diamond", None))
        self.action_Trapeze.setText(QCoreApplication.translate("MainWindow", u"\n"
"Trapeze", None))
        self.actionRight_Triangle.setText(QCoreApplication.translate("MainWindow", u"Right Triangle", None))
        self.action45.setText(QCoreApplication.translate("MainWindow", u"45", None))
        self.action90.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.action180.setText(QCoreApplication.translate("MainWindow", u"180", None))
        self.action270.setText(QCoreApplication.translate("MainWindow", u"270", None))
        self.action_Straight.setText(QCoreApplication.translate("MainWindow", u"\n"
"Straight", None))
        self.actionCube.setText(QCoreApplication.translate("MainWindow", u"Cube", None))
        self.actionPiramid.setText(QCoreApplication.translate("MainWindow", u"Piramid", None))
        self.actionBall.setText(QCoreApplication.translate("MainWindow", u"Ball", None))
        self.actionCone.setText(QCoreApplication.translate("MainWindow", u"Cone", None))
        self.action_Cylinder.setText(QCoreApplication.translate("MainWindow", u"\n"
"Cylinder", None))
        self.actionBlue.setText(QCoreApplication.translate("MainWindow", u"Blue", None))
        self.actionBlack.setText(QCoreApplication.translate("MainWindow", u"Black", None))
        self.actionRed.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionYellow.setText(QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.actionPurple.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionOrange.setText(QCoreApplication.translate("MainWindow", u"Orange", None))
        self.actionPink.setText(QCoreApplication.translate("MainWindow", u"Pink", None))
        self.actionCyan.setText(QCoreApplication.translate("MainWindow", u"Cyan", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
#if QT_CONFIG(shortcut)
        self.actionPen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionYellow_2.setText(QCoreApplication.translate("MainWindow", u"Yellow", None))
        self.actionPurple_2.setText(QCoreApplication.translate("MainWindow", u"Purple", None))
        self.actionRed_2.setText(QCoreApplication.translate("MainWindow", u"Red", None))
        self.actionCian.setText(QCoreApplication.translate("MainWindow", u"Cyan", None))
        self.actionCredits_2.setText(QCoreApplication.translate("MainWindow", u"Credits", None))
#if QT_CONFIG(shortcut)
        self.actionCredits_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionHelp_2.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.actionHelp_3.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.actionRectangle_2.setText(QCoreApplication.translate("MainWindow", u"Rectangle", None))
#if QT_CONFIG(shortcut)
        self.actionRectangle_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionstraight_line.setText(QCoreApplication.translate("MainWindow", u"Straight Line", None))
#if QT_CONFIG(shortcut)
        self.actionstraight_line.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionEllipse.setText(QCoreApplication.translate("MainWindow", u"Ellipse", None))
#if QT_CONFIG(shortcut)
        self.actionEllipse.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionLast_Page.setText(QCoreApplication.translate("MainWindow", u"Last Page", None))
#if QT_CONFIG(shortcut)
        self.actionLast_Page.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.actionFirst_Page.setText(QCoreApplication.translate("MainWindow", u"First Page", None))
#if QT_CONFIG(shortcut)
        self.actionFirst_Page.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Last_Page.setText(QCoreApplication.translate("MainWindow", u"Delete Last Page", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Last_Page.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_as_PNG.setText(QCoreApplication.translate("MainWindow", u"Save as PNG", None))
#if QT_CONFIG(shortcut)
        self.actionSave_as_PNG.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionPortugue_s.setText(QCoreApplication.translate("MainWindow", u"Portugu\u00eas", None))
        self.actionEspa_ol.setText(QCoreApplication.translate("MainWindow", u"Espa\u00f1ol", None))
        self.actionSave_all_as_PNG.setText(QCoreApplication.translate("MainWindow", u"Save all as PNG", None))
#if QT_CONFIG(shortcut)
        self.actionSave_all_as_PNG.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+R, Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_as_PDF.setText(QCoreApplication.translate("MainWindow", u"Save as PDF", None))
#if QT_CONFIG(shortcut)
        self.actionSave_as_PDF.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionHide_Cursor.setText(QCoreApplication.translate("MainWindow", u"Hide Cursor", None))
#if QT_CONFIG(shortcut)
        self.actionHide_Cursor.setShortcut(QCoreApplication.translate("MainWindow", u"F12", None))
#endif // QT_CONFIG(shortcut)
        self.actionSearch_Page.setText(QCoreApplication.translate("MainWindow", u"Search Page", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuPage.setTitle(QCoreApplication.translate("MainWindow", u"Page", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuPen.setTitle(QCoreApplication.translate("MainWindow", u"Pen Color", None))
        self.menuHighlighter_Color.setTitle(QCoreApplication.translate("MainWindow", u"Highlighter Color", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuTranslation.setTitle(QCoreApplication.translate("MainWindow", u"Translation", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

